### PR TITLE
Fix email string duplicate in registration page

### PR DESCRIPTION
**Pull request by lapinclown**
Fixes one part in registration popup where second occurrence of "email" is actually "username" to avoid confusion.

(wow)

### CODE REVIEW

**Comment by neksodebe** [comment]
LGTM

**Comment by neksodebe** [comment]
could you provide a screenshot of the new change working?

**Comment by SuromiDev** [comment]
image

**Comment by neksodebe** [comment]
looks good to me

**Comment by SuromiDev** [comment]
Polish (pl-PL): 
image

British English? (en-GB):
image

Russian (ru-RU):
image

Vietnamese (vi-VI):
image

**Comment by neksodebe** [comment]
looks good to me

**Pull request merged**
